# Generated by Django 5.0.14 on 2026-06-10 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Ciberneticos', 'Delegacia de Crimes Cibernéticos'), ('Idoso', 'Delegacia de Atendimento ao Idoso'), ('Procon', 'Procon'), ('Canal Online', 'Canal Online')], max_length=20, verbose_name='Tipo')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('horario', models.CharField(blank=True, max_length=100, verbose_name='Horário')),
                ('url', models.URLField(blank=True, verbose_name='Link')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Delegacia / Órgão',
                'verbose_name_plural': 'Delegacias / Órgãos',
                'ordering': ['cidade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('url_youtube', models.URLField(verbose_name='Link do Vídeo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Protocolo')),
                ('anonima', models.BooleanField(default=False, verbose_name='Denúncia anônima')),
                ('autor_hash', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='Identificador do autor')),
                ('tipo_golpe', models.CharField(choices=[('whatsapp_redes', 'Golpe do WhatsApp / Redes Sociais'), ('falso_banco', 'Falso funcionário de banco'), ('pix', 'Golpe do Pix'), ('promocao_falsa', 'Promoção ou Prêmio falso'), ('link_falso', 'Link ou página falsa'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de golpe')),
                ('data_ocorrencia', models.DateField(blank=True, null=True, verbose_name='Data da ocorrência')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=15, verbose_name='Status')),
                ('moderado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data da moderação')),
                ('motivo_moderacao', models.TextField(blank=True, verbose_name='Motivo da decisão')),
                ('publicada', models.BooleanField(default=False, verbose_name='Publicada')),
                ('publicada_em', models.DateTimeField(blank=True, null=True, verbose_name='Data da publicação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('moderado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_moderadas', to=settings.AUTH_USER_MODEL, verbose_name='Moderado por')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='portal_denu_status_912c50_idx'), models.Index(fields=['criado_em'], name='portal_denu_criado__4554f2_idx'), models.Index(fields=['autor_hash'], name='portal_denu_autor_h_32db24_idx')],
            },
        ),
    ]
