# Generated by Django 5.0.14 on 2026-06-07 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('url_youtube', models.URLField(verbose_name='Link do Vídeo (YouTube, etc.)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonima', models.BooleanField(default=False, help_text='Se True, o usuário real NÃO é rastreável. O campo "usuario" aponta para o usuário técnico fixo.', verbose_name='Denúncia anônima')),
                ('tipo_golpe', models.CharField(choices=[('whatsapp_redes', 'Golpe do WhatsApp / Redes Sociais'), ('falso_banco', 'Falso funcionário de banco'), ('pix', 'Golpe do Pix'), ('promocao_falsa', 'Promoção ou Prêmio falso'), ('link_falso', 'Link ou página falsa'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de golpe')),
                ('data_ocorrencia', models.DateField(blank=True, null=True, verbose_name='Data da ocorrência')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('descricao', models.TextField(help_text='Descrição fornecida pelo denunciante.', verbose_name='Descrição do ocorrido')),
                ('nome_informado', models.CharField(blank=True, help_text='Nome fornecido voluntariamente no formulário, se houver.', max_length=150, verbose_name='Nome informado (opcional)')),
                ('faixa_etaria', models.CharField(blank=True, choices=[('18_29', '18 a 29 anos'), ('30_44', '30 a 44 anos'), ('45_59', '45 a 59 anos'), ('60_mais', '60 anos ou mais')], max_length=10, verbose_name='Faixa etária')),
                ('status', models.CharField(choices=[('analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='analise', max_length=15, verbose_name='Status da Denúncia')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('usuario', models.ForeignKey(help_text='Para denúncias anônimas, aponta para o usuário técnico "anonimo_sistema" — nunca para o usuário real autenticado.', on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-criado_em'],
            },
        ),
    ]
