# Generated by Django 5.0.14 on 2026-06-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Ciberneticos', 'Delegacia de Crimes Cibernéticos'), ('Idoso', 'Delegacia de Atendimento ao Idoso'), ('Procon', 'Procon'), ('Canal Online', 'Canal Online')], max_length=20, verbose_name='Tipo')),
                ('cidade', models.CharField(blank=True, help_text='Deixe em branco para canais online/nacionais.', max_length=100, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('horario', models.CharField(blank=True, max_length=100, verbose_name='Horário de funcionamento')),
                ('url', models.URLField(blank=True, verbose_name='Link (para canais online)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Delegacia / Órgão',
                'verbose_name_plural': 'Delegacias / Órgãos',
                'ordering': ['cidade', 'nome'],
            },
        ),
    ]