# Generated by Django 5.0.14 on 2026-06-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='faixa_etaria',
            field=models.CharField(blank=True, choices=[('18_25', '18 a 25 anos'), ('26_35', '26 a 35 anos'), ('36_50', '36 a 50 anos'), ('51_65', '51 a 65 anos'), ('65_mais', 'Acima de 65 anos')], max_length=10, verbose_name='Faixa etária'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='autor_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Identificador do autor'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='analise', max_length=15, verbose_name='Status'),
        ),
    ]
