# Generated by Django 5.0.14 on 2026-06-08 23:15
from django.db import migrations, models

def criar_delegacias_iniciais(apps, schema_editor):
    Delegacia = apps.get_model('portal', 'Delegacia')

    # Dados das delegacias baseadas nos choices que seu colega criou
    delegacias = [
        {
            'nome': 'Delegacia de Crimes Cibernéticos de Palmas',
            'tipo': 'Ciberneticos',
            'cidade': 'Palmas',
            'endereco': 'Avenida Teotônio Segurado, Centro',
            'telefone': '(63) 3218-0000',
            'horario': '08:00 às 18:00',
            'url': '',
            'ativo': True
        },
        {
            'nome': 'Delegacia de Atendimento ao Idoso',
            'tipo': 'Idoso',
            'cidade': 'Palmas',
            'endereco': 'Quadra 602 Sul, ACSU-SE 60',
            'telefone': '(63) 3218-1111',
            'horario': '08:00 às 18:00',
            'url': '',
            'ativo': True
        },
        {
            'nome': 'Procon Tocantins',
            'tipo': 'Procon',
            'cidade': 'Palmas',
            'endereco': 'Quadra 104 Sul, Rua SE 09',
            'telefone': '151',
            'horario': '08:00 às 18:00',
            'url': 'https://procon.to.gov.br/',
            'ativo': True
        },
        {
            'nome': 'Canal Online de Denúncias',
            'tipo': 'Canal Online',
            'cidade': '',  # Em branco para canais online
            'endereco': '',
            'telefone': '',
            'horario': '24 Horas',
            'url': 'https://www.gov.br/disque100',
            'ativo': True
        },
    ]

    for dados in delegacias:
        if not Delegacia.objects.filter(nome=dados['nome'], cidade=dados['cidade']).exists():
            Delegacia.objects.create(**dados)

def remover_delegacias_iniciais(apps, schema_editor):
    Delegacia = apps.get_model('portal', 'Delegacia')
    # Remove as delegacias criadas se você der um rollback na migration
    Delegacia.objects.filter(
        tipo__in=['Ciberneticos', 'Idoso', 'Procon', 'Canal Online']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        # 1. Primeiro cria a tabela (Mantém o que seu colega fez)
        migrations.CreateModel(
            name='Delegacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Ciberneticos', 'Delegacia de Crimes Cibernéticos'), ('Idoso', 'Delegacia de Atendimento ao Idoso'), ('Procon', 'Procon'), ('Canal Online', 'Canal Online')], max_length=20, verbose_name='Tipo')),
                ('cidade', models.CharField(blank=True, help_text='Deixe em branco para canais online/nacionais.', max_length=100, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('horario', models.CharField(blank=True, max_length=100, verbose_name='Horário de funcionamento')),
                ('url', models.URLField(blank=True, verbose_name='Link (para canais online)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Delegacia / Órgão',
                'verbose_name_plural': 'Delegacias / Órgãos',
                'ordering': ['cidade', 'nome'],
            },
        ),
        # 2. Logo em seguida, roda a função para povoar os dados (Sua lógica)
        migrations.RunPython(criar_delegacias_iniciais, reverse_code=remover_delegacias_iniciais),
    ]